[package]
name = "icrc1"
version = "0.1.0"
description = "A libray with a full implementation of the ICRC-1 fungible token standard"

[dependencies]
base = "https://github.com/dfinity/motoko-base#a6301031d21449d38eb64a72e3e9dd0ad8447a86"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
Itertools = "https://github.com/NatLabs/Itertools.mo#main"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
