name: Makefile CI

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and internal tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.15.2
          
      - name: install mops
        run: |
            npm --yes -g i ic-mops
            mops i

#      - name: Detect warnings
#        run: make no-warn

      - name: Run Tests
        run: |
          make internal-tests
          
  icrc1-ref-test:
    runs-on: ubuntu-latest

    name: ICRC-1 reference test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.15.2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install mops
        run: |
            npm --yes -g i ic-mops
            mops i

      - name: Run reference tests
        run: |                                        
          dfx identity use default
          dfx identity new icrc-ref-test --force --storage-mode plaintext          
          dfx identity export default > ./icrc-ref-test.pem          
          dfx identity use icrc-ref-test                    
          dfx identity whoami                    
          make ref-test
          
          

      